import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../lib/auth';
import { accountRequest, type AccountData } from '../lib/accountApi';
export default function Account(){
 const {user,loading,signOut}=useAuth();const [data,setData]=useState<AccountData|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [contact,setContact]=useState({full_name:'',phone:'',city:''});
 const load=async()=>{try{const result=await accountRequest();setData(result);setContact({full_name:result.profile.full_name||'',phone:result.profile.phone||'',city:result.profile.city||''});}catch(e){setMessage(e instanceof Error?e.message:'Unable to load account.');}};
 useEffect(()=>{if(user)void load();else setData(null);},[user?.id]);
 const save=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{await accountRequest({action:'profile',...contact});setMessage('Contact details saved.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}};
 if(loading)return <main className="min-h-screen pt-32 text-center">Loading account…</main>;
 if(!user)return <main className="min-h-screen pt-32 text-center"><p>Sign in to manage your Campin account.</p><Link to="/auth" className="mt-4 inline-block underline">Sign in</Link></main>;
 return <main className="min-h-screen bg-offwhite px-4 pb-16 pt-28 text-forest"><div className="mx-auto max-w-3xl space-y-6"><h1 className="text-3xl font-bold">Your Campin account</h1><p>{user.email}</p>{message&&<p role="status">{message}</p>}{!data?<button onClick={()=>void load()} className="underline">Load account / Retry</button>:<><form onSubmit={save} className="space-y-4 rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">Contact details</h2>{(['full_name','phone','city'] as const).map(key=><label key={key} className="block text-sm font-bold">{{full_name:'Name',phone:'WhatsApp number with country code',city:'City'}[key]}<input required={key==='full_name'} type={key==='phone'?'tel':'text'} maxLength={key==='phone'?16:120} placeholder={key==='phone'?'+919876543210':''} value={contact[key]} onChange={e=>setContact({...contact,[key]:e.target.value})} className="mt-1 block w-full rounded-lg border p-3"/></label>)}<button disabled={busy} className="rounded-xl bg-forest px-5 py-3 text-white">{busy?'Saving…':'Save contact details'}</button></form><section className="rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">Saved campsites</h2>{data.favourites.length?data.favourites.map(f=><div key={f.listing_id} className="flex justify-between gap-4 border-b py-4"><Link className="underline" to={'/listing/'+f.listings.slug}>{f.listings.title}</Link><button onClick={async()=>{try{await accountRequest({action:'favourite',listingId:f.listing_id,saved:false});await load();}catch{setMessage('Could not remove campsite. Please retry.');}}}>Remove</button></div>):<p className="mt-3">No saved campsites yet. <Link to="/explore" className="underline">Explore campsites</Link></p>}</section><section className="rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">Your enquiries</h2>{data.enquiries.length?data.enquiries.map(e=><article key={e.id} className="border-b py-4"><p className="font-bold">{e.listings?.title||'Campsite no longer listed'}</p><p>{e.start_date?.slice(0,10)} – {e.end_date?.slice(0,10)} · {e.guests} guests</p><p className="text-sm">Reference: {e.tracking_id}</p><p className="text-sm">Request saved. Availability requires host confirmation.</p></article>):<p className="mt-3">No enquiries yet.</p>}</section></>}<button onClick={()=>void signOut()} className="rounded-xl border px-5 py-3">Sign out</button></div></main>;
}
