import { Link, useSearchParams } from 'react-router-dom';
import { useCatalogue, filterCampsites, campingStyles } from '../lib/catalogue';
import CampsiteCard from '../components/CampsiteCard';
import { blogPosts } from '../data/blogPosts';
import { campingGuides } from '../data/campingGuides';
export default function MarketplaceExplore(){
 const {campsites,loading,error}=useCatalogue(); const [params,setParams]=useSearchParams();
 const set=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next);};
 const results=filterCampsites(campsites,params); const query=(params.get('query')||'').toLowerCase();
 const resources=[...campingGuides.map(g=>({title:g.title,url:`/camping-guides/${g.slug}`})),...blogPosts.map(g=>({title:g.title,url:`/blog/${g.slug}`})),{title:'About Campin',url:'/about'},{title:'List your campsite',url:'/host-your-land'},{title:'Contact and help',url:'/support'}].filter(r=>query&&r.title.toLowerCase().includes(query)).slice(0,8);
 return <main className="min-h-screen bg-offwhite px-4 pb-20 pt-28 text-forest"><div className="mx-auto max-w-7xl">
 <form className="grid gap-3 rounded-2xl border border-forest/10 bg-white p-4 md:grid-cols-[2fr_1fr_1fr_.7fr_auto]" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const next=new URLSearchParams(params);for(const key of ['query','arrive','depart','guests']){const value=String(data.get(key)||'');value?next.set(key,value):next.delete(key);}setParams(next);}}>
 <label className="text-xs font-bold">Where to?<input key={params.get('query')} name="query" defaultValue={params.get('query')||''} placeholder="Destination, campsite or guide" className="mt-1 h-11 w-full rounded-lg bg-offwhite px-3 text-sm"/></label>
 <label className="text-xs font-bold">Arrival<input name="arrive" type="date" defaultValue={params.get('arrive')||''} className="mt-1 h-11 w-full rounded-lg bg-offwhite px-2"/></label><label className="text-xs font-bold">Departure<input name="depart" type="date" defaultValue={params.get('depart')||''} className="mt-1 h-11 w-full rounded-lg bg-offwhite px-2"/></label><label className="text-xs font-bold">Guests<input name="guests" type="number" min="1" max="50" defaultValue={params.get('guests')||2} className="mt-1 h-11 w-full rounded-lg bg-offwhite px-3"/></label><button className="self-end rounded-xl bg-orange px-6 py-3 font-bold text-white">Search</button></form>
 <p className="mt-2 text-xs text-textgrey">Dates are requests. Availability and total pricing require operator confirmation.</p>
 <div className="my-6 flex gap-2 overflow-x-auto pb-2"><button onClick={()=>set('style','')} className={`shrink-0 rounded-full border px-4 py-2 ${!params.get('style')?'bg-forest text-white':'bg-white'}`}>All stays</button>{campingStyles.map(([key,label])=><button key={key} onClick={()=>set('style',key)} className={`shrink-0 rounded-full border px-4 py-2 ${params.get('style')===key?'bg-forest text-white':'bg-white'}`}>{label}</button>)}</div>
 <div className="mb-8 flex flex-wrap gap-3"><select aria-label="State" value={params.get('state')||''} onChange={e=>set('state',e.target.value)} className="rounded-xl border p-3"><option value="">All states & territories</option>{[...new Set(campsites.map(c=>c.state))].sort().map(s=><option key={s}>{s}</option>)}</select><select aria-label="Amenity" value={params.get('amenity')||''} onChange={e=>set('amenity',e.target.value)} className="rounded-xl border p-3"><option value="">Any amenity</option>{[...new Set(campsites.flatMap(c=>c.amenities))].sort().map(s=><option key={s}>{s}</option>)}</select><select aria-label="Sort campsites" value={params.get('sort')||''} onChange={e=>set('sort',e.target.value)} className="rounded-xl border p-3"><option value="">Recommended</option><option value="price">Price: low to high</option><option value="name">Name: A–Z</option></select><label className="rounded-xl border bg-white p-3 text-sm">Max ₹ <input aria-label="Maximum nightly price" type="number" min="0" value={params.get('maxPrice')||''} onChange={e=>set('maxPrice',e.target.value)} className="w-24"/></label></div>
 <div className="mb-6 flex items-center justify-between gap-3"><h1 className="font-serif text-3xl font-bold">{query?'Search results':'Recommended campsites'}</h1><span className="text-sm">{results.length} places</span></div>
 {loading&&<p role="status">Loading campsites…</p>}{error&&<p role="alert">{error} <button onClick={()=>window.location.reload()} className="underline">Retry</button></p>}
 <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{results.map(site=><CampsiteCard key={site.id} site={site}/>)}</div>
 {!loading&&!error&&!results.length&&<div className="rounded-2xl bg-white p-8"><h2 className="text-xl font-bold">No places match these filters yet</h2><p className="my-3">Try another state or camping style.</p><button className="mr-5 font-bold underline" onClick={()=>setParams({})}>Reset filters</button><Link to="/suggest-campsite" className="font-bold text-orange underline">Suggest a campsite</Link></div>}
 {resources.length>0&&<section className="mt-12"><h2 className="text-2xl font-bold">Resources & help</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{resources.map(r=><Link key={r.url} to={r.url} className="rounded-xl bg-white p-4 underline">{r.title}</Link>)}</div></section>}
 <Link to="/suggest-campsite" className="mt-10 inline-block font-bold text-orange underline">Know a great place? Suggest a campsite</Link>
 </div></main>;
}
