import { Link, useSearchParams } from 'react-router-dom';
import { useCatalogue, filterCampsites, campingStyles } from '../lib/catalogue';
import CampsiteCard from '../components/CampsiteCard';
import { searchPublicResources } from '../lib/publicSearch';
import TripSearch from '../components/TripSearch';
export default function MarketplaceExplore(){
 const {campsites,loading,error}=useCatalogue(); const [params,setParams]=useSearchParams();
 const set=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next);};
 const results=filterCampsites(campsites,params); const query=params.get('query')||'';
 const activeStyles=campingStyles;
 const resources=searchPublicResources(query);
 return <main className="min-h-screen bg-offwhite px-4 pb-20 pt-28 text-forest"><div className="mx-auto max-w-7xl">
 <TripSearch key={`${params.get('query')}-${params.get('arrive')}-${params.get('depart')}-${params.get('guests')}`} compact initial={{query:params.get('query')||'',arrive:params.get('arrive')||'',depart:params.get('depart')||'',guests:Number(params.get('guests'))||2}} onSearch={next=>{const merged=new URLSearchParams(params);for(const key of ['query','arrive','depart','guests']){const value=next.get(key);value?merged.set(key,value):merged.delete(key);}setParams(merged)}}/>
 <p className="mt-2 text-xs text-textgrey">Dates are requests. Availability and total pricing require operator confirmation.</p>
 <div className="my-6 flex gap-2 overflow-x-auto pb-2"><button onClick={()=>set('style','')} className={`shrink-0 rounded-full border px-4 py-2 ${!params.get('style')?'bg-forest text-white':'bg-white'}`}>All stays <span className="ml-1 opacity-70">{campsites.length}</span></button>{activeStyles.map(([key,label])=>{const count=campsites.filter(c=>c.styles.includes(key)).length;return <button key={key} onClick={()=>set('style',key)} className={`shrink-0 rounded-full border px-4 py-2 ${params.get('style')===key?'bg-forest text-white':'bg-white'}`}>{label} <span className="ml-1 opacity-70">{count}</span></button>})}</div>
 <div className="mb-8 flex flex-wrap gap-3"><select aria-label="State" value={params.get('state')||''} onChange={e=>set('state',e.target.value)} className="rounded-xl border p-3"><option value="">All states & territories</option>{[...new Set(campsites.map(c=>c.state))].sort().map(s=><option key={s}>{s}</option>)}</select><select aria-label="Amenity" value={params.get('amenity')||''} onChange={e=>set('amenity',e.target.value)} className="rounded-xl border p-3"><option value="">Any amenity</option>{[...new Set(campsites.flatMap(c=>c.amenities))].sort().map(s=><option key={s}>{s}</option>)}</select><select aria-label="Sort campsites" value={params.get('sort')||''} onChange={e=>set('sort',e.target.value)} className="rounded-xl border p-3"><option value="">Recommended</option><option value="price">Price: low to high</option><option value="name">Name: A–Z</option></select><label className="rounded-xl border bg-white p-3 text-sm">Max ₹ <input aria-label="Maximum nightly price" type="number" min="0" value={params.get('maxPrice')||''} onChange={e=>set('maxPrice',e.target.value)} className="w-24"/></label></div>
 <div className="mb-6 flex items-center justify-between gap-3"><div><h1 className="font-serif text-3xl font-bold">{query?'Search results':'Recommended campsites'}</h1>{(params.get('arrive')&&params.get('depart'))&&<p className="mt-1 text-sm text-textgrey">Requested trip: {params.get('arrive')} to {params.get('depart')} · {params.get('guests')||2} guests</p>}</div><span className="text-sm">{results.length} places</span></div>
 {loading&&<p role="status">Loading campsites…</p>}{error&&<p role="alert">{error} <button onClick={()=>window.location.reload()} className="underline">Retry</button></p>}
 <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{results.map(site=><CampsiteCard key={site.id} site={site}/>)}</div>
 {!loading&&!error&&!results.length&&<div className="rounded-2xl bg-white p-8"><h2 className="text-xl font-bold">No places match these filters yet</h2><p className="my-3">Try another state or camping style.</p><button className="mr-5 font-bold underline" onClick={()=>setParams({})}>Reset filters</button><Link to="/suggest-campsite" className="font-bold text-orange underline">Suggest a campsite</Link></div>}
 {resources.length>0&&<section className="mt-12"><h2 className="text-2xl font-bold">Guides, articles & help</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{resources.map(r=><Link key={r.href} to={r.href} className="rounded-xl bg-white p-4 hover:shadow-sm"><span className="text-xs font-bold uppercase tracking-wide text-orange">{r.kind}</span><span className="mt-2 block font-bold underline">{r.title}</span><span className="mt-1 block text-sm text-textgrey">{r.description}</span></Link>)}</div></section>}
 <Link to="/suggest-campsite" className="mt-10 inline-block font-bold text-orange underline">Know a great place? Suggest a campsite</Link>
 </div></main>;
}
