import { useState, type FormEvent } from 'react';
import { Search, Minus, Plus, Users } from 'lucide-react';
import { draftToParams, nextDate, todayIso, validateTrip, type TripDraft } from '../lib/tripSearch';
export default function TripSearch({initial,onSearch,compact=false}:{initial?:Partial<TripDraft>;onSearch:(params:URLSearchParams)=>void;compact?:boolean}){
 const [draft,setDraft]=useState<TripDraft>({query:initial?.query||'',arrive:initial?.arrive||'',depart:initial?.depart||'',guests:initial?.guests||2});const [error,setError]=useState('');
 const submit=(event:FormEvent)=>{event.preventDefault();const message=validateTrip(draft);setError(message);if(!message)onSearch(draftToParams(draft));};
 const guests=(next:number)=>setDraft({...draft,guests:Math.max(1,Math.min(50,next))});
 return <form onSubmit={submit} className={`grid gap-2 rounded-2xl bg-white p-2 text-forest shadow-xl ${compact?'lg:grid-cols-[1.6fr_1fr_1fr_1fr_auto]':'md:grid-cols-[1.5fr_1fr_1fr_1fr_auto]'}`}>
 <label className="min-w-0"><span className="sr-only">Destination, campsite or guide</span><input value={draft.query} onChange={e=>setDraft({...draft,query:e.target.value})} placeholder="Destination, campsite or guide" className="h-12 w-full rounded-xl bg-offwhite px-4 text-sm font-bold outline-none focus:ring-2 focus:ring-orange"/></label>
 <label className="min-w-0"><span className="block px-2 text-xs font-bold">Arrival date</span><input value={draft.arrive} onChange={e=>setDraft({...draft,arrive:e.target.value,depart:draft.depart&&draft.depart<=e.target.value?'':draft.depart})} min={todayIso()} type="date" aria-label="Arrival date" className="h-12 w-full rounded-xl bg-offwhite px-3 text-sm"/></label>
 <label className="min-w-0"><span className="block px-2 text-xs font-bold">Departure date</span><input value={draft.depart} onChange={e=>setDraft({...draft,depart:e.target.value})} min={draft.arrive?nextDate(draft.arrive):nextDate(todayIso())} type="date" aria-label="Departure date" className="h-12 w-full rounded-xl bg-offwhite px-3 text-sm"/></label>
 <div className="flex h-12 items-center justify-between rounded-xl bg-offwhite px-2"><Users size={16} className="ml-1 text-orange"/><button disabled={draft.guests <= 1} aria-label="Remove guest" type="button" onClick={()=>guests(draft.guests-1)} className="grid h-8 w-8 place-items-center rounded-full hover:bg-white"><Minus size={15}/></button><span aria-label={`${draft.guests} guests`} className="min-w-8 text-center text-sm font-bold">{draft.guests}</span><button disabled={draft.guests >= 50} aria-label="Add guest" type="button" onClick={()=>guests(draft.guests+1)} className="grid h-8 w-8 place-items-center rounded-full hover:bg-white"><Plus size={15}/></button></div>
 <button className="flex h-12 items-center justify-center gap-2 rounded-xl bg-orange px-6 text-sm font-black text-white hover:bg-orange-dark"><Search size={17}/>Search</button><button type="button" onClick={()=>{setDraft({...draft,arrive:"",depart:""});setError("");}} className="col-span-full text-left px-2 text-xs underline">Flexible dates · clear dates</button>{error&&<p role="alert" className="col-span-full px-2 pt-1 text-sm font-semibold text-red-700">{error}</p>}</form>;
}
