-- Public fields only. A source-reviewed listing is not a Campin partnership,
-- availability guarantee, or WhatsApp consent from the operator.
alter table public.listings add column if not exists catalogue_details jsonb not null default '{}'::jsonb;

with source(name,slug,region,state,listing_type,summary,price,amenities,details) as (
 values
 ('Bheemeshwari Adventure and Nature Camp','bheemeshwari-nature-camp','Bheemeshwari','Karnataka','forest','Official Jungle Lodges & Resorts nature camp near the Cauvery with packages and activities shown on its property page.',5740,'["Parking","Breakfast","Nature walk"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/bheemeshwari-adventure-and-nature-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Parking","Breakfast","Nature walk"],"verification":"source-reviewed"}'::jsonb),
 ('Galibore Nature Camp','galibore-nature-camp','Kanakapura','Karnataka','forest','Official Jungle Lodges & Resorts nature camp on the Cauvery; the operator lists tented cottages, nature walks and package pricing.',4814,'["Tented cottages","Parking","Guided trekking"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/galibore-nature-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Tented cottages","Parking","Guided trekking"],"verification":"source-reviewed"}'::jsonb),
 ('Bannerghatta Nature Camp','bannerghatta-nature-camp','Bengaluru','Karnataka','forest','Official Jungle Lodges & Resorts stay near Bannerghatta with operator-listed accommodation and safari packages.',6487,'["Parking","Breakfast","Safari package"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/bannerghatta-nature-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Parking","Breakfast","Safari package"],"verification":"source-reviewed"}'::jsonb),
 ('K. Gudi Wilderness Camp','k-gudi-wilderness-camp','BRT Wildlife Sanctuary','Karnataka','forest','Official Jungle Lodges & Resorts wilderness camp; the operator lists tent and loghut packages.',6635,'["Tents","Parking","Nature walk"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/k-gudi-wilderness-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Tents","Parking","Nature walk"],"verification":"source-reviewed"}'::jsonb),
 ('Kali Adventure Camp','kali-adventure-camp','Dandeli','Karnataka','forest','Official Jungle Lodges & Resorts adventure camp in the Kali region; package details are maintained by the operator.',4342,'["Parking","Breakfast","Nature walk"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/kali-adventure-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Parking","Breakfast","Nature walk"],"verification":"source-reviewed"}'::jsonb),
 ('Bhagawathi Nature Camp','bhagawathi-nature-camp','Kudremukh','Karnataka','forest','Official Jungle Lodges & Resorts camp in the Kudremukh area with tents and a dormitory shown by the operator.',2985,'["Tents","Parking","Nature walk"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/bhagawathi-nature-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Tents","Parking","Nature walk"],"verification":"source-reviewed"}'::jsonb),
 ('Anejhari Butterfly Camp','anejhari-butterfly-camp','Kollur','Karnataka','forest','Official Jungle Lodges & Resorts camp with operator-listed wooden cottages, tented cottages and dormitory accommodation.',2242,'["Tented cottages","Parking","Trekking"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/anejhari-butterfly-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Tented cottages","Parking","Trekking"],"verification":"source-reviewed"}'::jsonb),
 ('Seethanadi Nature Camp','seethanadi-nature-camp','Udupi','Karnataka','forest','Official Jungle Lodges & Resorts camp with operator-listed tents, cottages and dormitory options.',2602,'["Tents","Parking","Trekking"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/seethanadi-nature-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Tents","Parking","Trekking"],"verification":"source-reviewed"}'::jsonb),
 ('Gopinatham Mystery Trails','gopinatham-mystery-trails','Gopinatham','Karnataka','forest','Official Jungle Lodges & Resorts tented-cottage nature stay; trip details and pricing are on the operator page.',null,'["Tented cottages","Parking","Nature trail"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/gopinatham-mystery-trails/","styles":["hosted-tent","nature-stay"],"amenities":["Tented cottages","Parking","Nature trail"],"verification":"source-reviewed"}'::jsonb),
 ('Sharavathi Adventure Camp','sharavathi-adventure-camp','Jog Falls','Karnataka','forest','Official Jungle Lodges & Resorts adventure camp in the Jog Falls area with operator-listed cottages and activities.',4213,'["Parking","Breakfast","Nature walk"]'::jsonb,'{"operator":"Jungle Lodges & Resorts","sourceUrl":"https://www.junglelodges.com/resort/sharavathi-adventure-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Parking","Breakfast","Nature walk"],"verification":"source-reviewed"}'::jsonb),
 ('KAVA Eco Camp and Caravan Park','kava-eco-camp-caravan-park','Malampuzha','Kerala','caravan_park','Kerala Tourism describes this Malampuzha caravan park as having large-caravan and camper-van capacity plus charging, water and waste facilities.',null,'["Caravan bays","Campervan bays","Electric charging","Drinking water"]'::jsonb,'{"operator":"KAVA Eco Camp and Caravan Park","sourceUrl":"https://www.keralatourism.org/newsletter/news/2025/kava-eco-camp-and-caravan-park-a-new-benchmark/2292","styles":["campervan","road-stop"],"amenities":["Caravan bays","Campervan bays","Electric charging","Drinking water"],"verification":"source-reviewed"}'::jsonb),
 ('Caravan Meadows','caravan-meadows-vagamon','Vagamon','Kerala','caravan_park','Kerala Tourism lists this caravan park at Nallathanni on the Vagamon–Elappara Road with water, electric points and waste handling.',null,'["Campervan bays","Electric charging","Drinking water"]'::jsonb,'{"operator":"Caravan Meadows","sourceUrl":"https://www.keralatourism.org/newsletter/news/2022/wagamon-caravan-park/2058","styles":["campervan","road-stop"],"amenities":["Campervan bays","Electric charging","Drinking water"],"verification":"source-reviewed"}'::jsonb),
 ('Pangong Delight Camp','pangong-delight-camp','Pangong Lake','Ladakh','desert','Camps of Ladakh lists Pangong Delight Camp among its Pangong stays. Confirm seasonal operation directly with the operator.',null,'["Mountain view","Parking"]'::jsonb,'{"operator":"Camps of Ladakh","sourceUrl":"https://campsofladakh.com/stay_detail/pangong-delight-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Mountain view","Parking"],"verification":"source-reviewed"}'::jsonb),
 ('Avalon Camp','avalon-camp','Nubra Valley','Ladakh','desert','Camps of Ladakh lists Avalon Camp in Nubra Valley. Confirm current seasonal availability and itinerary directly with the operator.',5040,'["Mountain view","Parking"]'::jsonb,'{"operator":"Camps of Ladakh","sourceUrl":"https://campsofladakh.com/stay_detail/avalon-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Mountain view","Parking"],"verification":"source-reviewed"}'::jsonb),
 ('Nubra Delight Camp','nubra-delight-camp','Nubra Valley','Ladakh','desert','Camps of Ladakh lists Nubra Delight Camp in Hunder. Confirm current seasonal availability directly with the operator.',12000,'["Mountain view","Parking"]'::jsonb,'{"operator":"Camps of Ladakh","sourceUrl":"https://campsofladakh.com/stay_detail/nubra-delight-camp/","styles":["hosted-tent","nature-stay"],"amenities":["Mountain view","Parking"],"verification":"source-reviewed"}'::jsonb)
), h as (insert into public.hosts(name,segment,region,state,public_url) select details->>'operator','operator',min(region),min(state),min(details->>'sourceUrl') from source group by details->>'operator' returning id,name), p as (insert into public.properties(host_id,name,slug,region,state) select h.id,s.name,s.slug,s.region,s.state from source s join h on h.name=s.details->>'operator' returning id,slug)
insert into public.listings(property_id,slug,title,listing_type,verification_stage,availability_mode,contact_policy,public_summary,price_from_inr,price_unit,essentials,unknowns,last_checked_at,is_published,published_at,catalogue_details)
select p.id,s.slug,s.name,s.listing_type::listing_type,'reviewed','request_to_book','campin_review_required',s.summary,s.price,'person/night',s.amenities,'["Live availability","Campin host contact"]'::jsonb,now(),true,now(),s.details from source s join p on p.slug=s.slug;
